/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/auth/confirm-signup': RouteRecordInfo<'/auth/confirm-signup', '/auth/confirm-signup', Record<never, never>, Record<never, never>>,
    '/auth/forgot-password': RouteRecordInfo<'/auth/forgot-password', '/auth/forgot-password', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/signup': RouteRecordInfo<'/auth/signup', '/auth/signup', Record<never, never>, Record<never, never>>,
    '/folder': RouteRecordInfo<'/folder', '/folder', Record<never, never>, Record<never, never>, '/folder/[email]'>,
    '/folder/[email]': RouteRecordInfo<'/folder/[email]', '/folder/:email', { email: ParamValue<true> }, { email: ParamValue<false> }>,
    '/liveStream': RouteRecordInfo<'/liveStream', '/liveStream', Record<never, never>, Record<never, never>>,
    '/persons': RouteRecordInfo<'/persons', '/persons', Record<never, never>, Record<never, never>, '/persons/[id]'>,
    '/persons/[id]': RouteRecordInfo<'/persons/[id]', '/persons/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/photo/[id]': RouteRecordInfo<'/photo/[id]', '/photo/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
  }
}
